import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { headers } from "next/headers";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Presensi FILKOM — Universitas Klabat",
  description: "Sistem Presensi Kuliah Umum & Chapel FILKOM Universitas Klabat",
  keywords: ["presensi", "filkom", "kuliah umum", "chapel", "universitas klabat"],
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Read the CSP nonce generated by middleware for inline scripts/styles
  const nonce = (await headers()).get("x-nonce") ?? undefined;

  return (
    <html lang="id" nonce={nonce}>
      <body className={`${inter.variable} font-sans antialiased`}>
        {children}
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
